name: Setup Environment Action
description: 'Setup the environment for any Open Logic jobs'

inputs:
  os:
    description: 'The runner OS'
    required: true

runs:
  using: 'composite'
  steps:
    #Python Setup (Cached)
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python Requiremetns
      shell: bash
      run: pip install -r ./.github/workflows/requirements.txt
    #Setup APT Get packages (Uncached - complex and little benefit in time)
    - name: Install APT packages
      shell: bash
      run: |
        sudo apt-get update
        xargs -a .github/workflows/apt-dependencies.txt sudo apt-get install -y
    #Setup GHDL (Uncached - no benefit in time)
    - name: Download and extract GHDL
      shell: bash
      run: |
        mkdir -p ~/ghdl
        wget https://github.com/ghdl/ghdl/releases/download/v3.0.0/ghdl-gha-ubuntu-20.04-mcode.tgz
        tar zxvf ghdl-gha-ubuntu-20.04-mcode.tgz -C ~/ghdl
    - name: Add GHDL to PATH
      shell: bash
      run: echo "$HOME/ghdl/bin" >> $GITHUB_PATH
    #Setup Modelsim
    - name: Install ModelSim dependencies
      shell: bash
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install lib32z1 lib32stdc++6 libexpat1:i386 libc6:i386 libsm6:i386 libncurses5:i386 libx11-6:i386 zlib1g:i386 libxext6:i386 libxft2:i386
    # Save time on subsequent runs by caching the install of ModelSim.
    # Download is ~1.5GB and combined with the installation process it takes over 3 minutes.
    - name: Cache ModelSim
      shell: bash
      uses: actions/cache@v2
      with:
        path: $HOME/intelFPGA
        key: ${{ runner.os }}-modelsim
    - name: Install ModelSim if not cached
      shell: bash
      run: stat $HOME/intelFPGA/20.1/modelsim_ase || (curl 'https://download.altera.com/akdlm/software/acdsinst/20.1std.1/720/ib_installers/ModelSimSetup-20.1.1.720-linux.run' -o ModelSimSetup.run && chmod +x ModelSimSetup.run && ./ModelSimSetup.run --mode unattended --accept_eula 1 && sed -i 's/linux_rh60/linux/g' $HOME/intelFPGA/20.1/modelsim_ase/vco )
    - name: Add ModelSim to PATH
      shell: bash
      run: echo "$HOME/intelFPGA/20.1/modelsim_ase/bin" >> $GITHUB_PATH

